<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/restaurant.proto

namespace Restaurant_service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>restaurant_service.AddRestaurantResponse</code>
 */
class AddRestaurantResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 res_id = 1;</code>
     */
    private $res_id = 0;
    /**
     * Generated from protobuf field <code>.restaurant_service.Status status = 2;</code>
     */
    private $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $res_id
     *     @type \Restaurant_service\Status $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Restaurant::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 res_id = 1;</code>
     * @return int|string
     */
    public function getResId()
    {
        return $this->res_id;
    }

    /**
     * Generated from protobuf field <code>uint64 res_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResId($var)
    {
        GPBUtil::checkUint64($var);
        $this->res_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.restaurant_service.Status status = 2;</code>
     * @return \Restaurant_service\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.restaurant_service.Status status = 2;</code>
     * @param \Restaurant_service\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Restaurant_service\Status::class);
        $this->status = $var;

        return $this;
    }

}

