<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/restaurant.proto

namespace Restaurant_service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>restaurant_service.Restaurant</code>
 */
class Restaurant extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 res_id = 1;</code>
     */
    private $res_id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>double rating = 3;</code>
     */
    private $rating = 0.0;
    /**
     * Generated from protobuf field <code>repeated string cuisines = 4;</code>
     */
    private $cuisines;
    /**
     * Generated from protobuf field <code>double cost_for_two = 5;</code>
     */
    private $cost_for_two = 0.0;
    /**
     * Generated from protobuf field <code>string opening_time = 6;</code>
     */
    private $opening_time = '';
    /**
     * Generated from protobuf field <code>string closing_time = 7;</code>
     */
    private $closing_time = '';
    /**
     * Generated from protobuf field <code>.restaurant_service.Restaurant.Location location = 8;</code>
     */
    private $location = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $res_id
     *     @type string $name
     *     @type float $rating
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $cuisines
     *     @type float $cost_for_two
     *     @type string $opening_time
     *     @type string $closing_time
     *     @type \Restaurant_service\Restaurant\Location $location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Restaurant::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 res_id = 1;</code>
     * @return int|string
     */
    public function getResId()
    {
        return $this->res_id;
    }

    /**
     * Generated from protobuf field <code>uint64 res_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResId($var)
    {
        GPBUtil::checkUint64($var);
        $this->res_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double rating = 3;</code>
     * @return float
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Generated from protobuf field <code>double rating = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setRating($var)
    {
        GPBUtil::checkDouble($var);
        $this->rating = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string cuisines = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCuisines()
    {
        return $this->cuisines;
    }

    /**
     * Generated from protobuf field <code>repeated string cuisines = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCuisines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cuisines = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double cost_for_two = 5;</code>
     * @return float
     */
    public function getCostForTwo()
    {
        return $this->cost_for_two;
    }

    /**
     * Generated from protobuf field <code>double cost_for_two = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setCostForTwo($var)
    {
        GPBUtil::checkDouble($var);
        $this->cost_for_two = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string opening_time = 6;</code>
     * @return string
     */
    public function getOpeningTime()
    {
        return $this->opening_time;
    }

    /**
     * Generated from protobuf field <code>string opening_time = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOpeningTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->opening_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string closing_time = 7;</code>
     * @return string
     */
    public function getClosingTime()
    {
        return $this->closing_time;
    }

    /**
     * Generated from protobuf field <code>string closing_time = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClosingTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->closing_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.restaurant_service.Restaurant.Location location = 8;</code>
     * @return \Restaurant_service\Restaurant\Location
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.restaurant_service.Restaurant.Location location = 8;</code>
     * @param \Restaurant_service\Restaurant\Location $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Restaurant_service\Restaurant_Location::class);
        $this->location = $var;

        return $this;
    }

}

