<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/restaurant.proto

namespace Restaurant_service;

if (false) {
    /**
     * This class is deprecated. Use Restaurant_service\Restaurant\Location instead.
     * @deprecated
     */
    class Restaurant_Location {}
}
class_exists(Restaurant\Location::class);
@trigger_error('Restaurant_service\Restaurant_Location is deprecated and will be removed in the next major release. Use Restaurant_service\Restaurant\Location instead', E_USER_DEPRECATED);

