<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/restaurant.proto

namespace Restaurant_service;

if (false) {
    /**
     * This class is deprecated. Use Restaurant_service\Status\StatusCode instead.
     * @deprecated
     */
    class Status_StatusCode {}
}
class_exists(Status\StatusCode::class);
@trigger_error('Restaurant_service\Status_StatusCode is deprecated and will be removed in the next major release. Use Restaurant_service\Status\StatusCode instead', E_USER_DEPRECATED);

